# Generated by Django 2.2 on 2024-01-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygym', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
