# Generated by Django 2.2 on 2024-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygym', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
