# Generated by Django 2.2 on 2024-01-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygym', '0005_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
    ]
