# Generated by Django 2.2 on 2024-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygym', '0006_remove_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
